import logoTikTok from "/assets/iconTiktokWhite.jpg";
import logoInstagram from "/assets/iconInstaWhite.jpg";
import logoYoutube from "/assets/iconYouWhite.jpg";


export const Etiqueta = [
  { name: 'Musica', href: '#', id: 1 },
  { name: 'Nosotros', href: '#', id: 2 },
  { name: 'Actualidad', href: '#', id: 3 },
  { name: 'Comedia', href: '#', id: 4 }
];

export const LinksItems = [
  { logo: logoYoutube, href: 'https://www.youtube.com/@Ultraverselr', id: 1 },
  { logo: logoInstagram, href: 'https://www.instagram.com/malditoclub.ok/', id: 2 },
  { logo: logoTikTok, href: 'https://www.tiktok.com/%40malditoclub?fbclid=PAb21jcAQc1ntleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAac0NGJsh-vKN_jrV6vdohKlFoa81Fwa665lwe1ZULp4LCuhRRX6nrrfZdsqsA_aem_T1o1GzP42K66y10u76fOoA', id: 3 },
];

export const Noticias = [
  { 
    titulo: "El vuelo de Adorni a Punta del Este: el broker que vendió el pasaje de vuelta declaró que pagó Marcelo Grandío", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "imagen1.avif",
    texto: [
        "El testigo ratificó que quien pagó, tanto la ida como la vuelta, fue Marcelo Grandío, quien pasó el fin de semana largo de carnaval con el jefe de Gabinete, sus dos hijos y su esposa. Issin había dicho al diario La Nación y repitió ahora ante la Justicia que adquirió un paquete de 10 vuelos -que incluyen ida y vuelta- por 42.250 dólares a la empresa Alpha Centauri.No obstante, la facturación que consta en el expediente se hizo por separado para el periodista amigo de Adorni. La ida se la cobró Alpha Centauri a la productora ImHouse, y la vuelta la facturó el bróker directamente a Grandío. La factura del viaje de regreso a Buenos Aires se emitió el 9 de marzo -tres semanas después del vuelo- y fue por un valor de 3.000 dólares. Una novedad que surgió de la declaración del piloto es que Marcelo Grandío pagó en efectivo e hizo llegar los billetes a través de un tal “Horacio”, según confiaron a Infobae fuentes del caso. En la testimonial, además, el bróker Issin fue consultado sobre por qué vendió el vuelo a 3.000 dólares, ya que no cerraría con el “precio mayorista” que él pagó por el paquete, y a qué se debe la facturación tardía. El intermediario entre los clientes exclusivos y esta compañía de aviación privada explicó sobre este point que “si el cliente necesita bajar los costos por un determinado motivo, es usual utilizar la ‘pata vacía’ –empty leg, como se le llama en el rubro- para vendérsela a otros clientes”. Y agregó que “puede pasar que el cliente quiera partir del destino B hacia el destino A, por lo que el avión, que está en el destino A, tiene que movilizarse hacia B. Ese tramo (de A hacia B) queda vacío y el cliente puede pedir que se utilice ese espacio para otro pasajero y así aminorar el costo”. Tal fue el caso de Adorni y Grandio, según el piloto: pudieron ubicar en el viaje de ida a otros dos pasajeros y en la vuelta a uno en asientos libres, lo que generó un descuento en el precio. El testigo había sido consultado por la prensa respecto de más precisiones sobre esto cuando salió del Juzgado Federal N° 4, pero prefirió guardar silencio: “No quiero hablar al respecto, pero está aclarado ese point. También aclaré quién pagó”, dijo. El miércoles, en conferencia de prensa, Manuel Adorni había declarado: “El viaje lo pagué, estoy cansado de decirlo, ya no sé cómo explicarlo. La dádiva está si yo no hubiera pagado el viaje”."],
    etiqueta: 1
  },
  { 
    titulo: "Muere Noelia Castillo, la más joven en recibir la eutanasia en España, tras dos años de lucha en los tribunales", 
    introduccion: "Los nuevos chips prometen revolucionar la eficiencia energética en portátiles con arquitectura híbrida avanzada.",
    imagen: "imagen2.avif",
    texto: ["Noelia Castillo, la joven parapléjica de 25 años que había pedido la eutanasia, ha fallecido este jueves después de recibir la muerte asistida en su habitación de la residencia sociosanitaria de Sant Pere de Ribes. Noelia es la paciente más joven de España en recibir la eutanasia y la sexta paciente psiquiátrica de Cataluña en pasar por este procedimiento. Su eutanasia debió llevarse a cabo hace dos años, el 2 de agosto de 2024, pero una orden judicial paralizó el procedimiento in extremis a petición de su padre. Durante dos años, el hombre ha intentado de la mano de Abogados Cristianos impedir la muerte asistida de su hija y ha llevado su demanda hasta el Tribunal Europeo de Derechos Humanos (TEDH), sin éxito. Finalmente, la eutanasia de Noelia quedó programada para este jueves, 26 de marzo. La joven ha fallecido sola y después de despedirse de su madre, tal y como deseaba, en la residencia sociosanitaria de Sant Pere de Ribes donde estaba ingresada y que consideraba como su “zona de confort”, según expresó en una entrevista en el programa Ahora Sonsoles. “Quiero irme ya y dejar de sufrir y punto. Ninguno de mi familia está a favor de la eutanasia. ¿Y yo todo el dolor que he sufrido durante todos estos años?“, expresó durante su entrevista en Antena 3. La joven planeaba ponerse “el vestido más bonito” de su armario y maquillarse de forma “sencilla” para el momento. “Siempre he pensado que quiero morirme guapa”, aseguró. Noelia se crio en una familia desestructurada, marcada por las adicciones y problemas de salud mental de su padre, que hicieron que la joven pasara gran parte de su infancia y adolescencia en centros de menores. El evento que marcó esta historia fue, para ella, una agresión sexual múltiple que sufrió en 2022. Poco después, en octubre del mismo año, la joven intentó suicidarse, incidente por el que quedó parapléjica."],
    etiqueta: 2
  },
  { 
    titulo: "“¿Qué hacés que no le contestás el teléfono a Scaloni?“: la increíble secuencia de la citación de uno de los jugadores de Argentina", 
    introduccion: "Los nuevos procesadores basados en arquitectura Zen 5 establecen nuevos récords de rendimiento.",
    imagen: "imagen3.avif",
    texto: ["La convocatoria a último momento de Agustín Giay a la selección argentina resultó una de las grandes novedades de la nómina del director técnico Lionel Scaloni de cara a los amistosos ante Mauritania y Zambia en La Bombonera. En las últimas horas, se dieron a conocer los entretelones del llamado, que incluyó una verdadera pieza de comedia. Fue su papá el encargado de contar los detalles de lo sucedido con el lateral del Palmeiras, de 22 años. Giay, surgido de San Lorenzo, fue citado para suplir a Gonzalo Montiel, marginado por un desgarro en el isquiotibial. Su reacción, según relató Cadena 3, fue de sorpresa y alegría absoluta. El propio Giay se enteró a través de una llamada insistente de su padre, quien había sido advertido primero por el representante del futbolista. La convocatoria coincidió con días libres que Giay disfrutaba en la capital argentina y motivó un inmediato festejo familiar. El camino que desembocó en la citación comenzó con el rumor transmitido por el apoderado de Giay. “El representante de Agustín me comenta que se rumoreaba que existía la posibilidad de que lo convoquen, pero eran solo comentarios, hasta que 30 minutos después me vuelve a llamar para confirmarlo”, relató Maximiliano Giay a Cadena 3."],
    etiqueta: 3
  },
  { 
    titulo: "El vuelo de Adorni a Punta del Este: el broker que vendió el pasaje de vuelta declaró que pagó Marcelo Grandío", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "imagen1.avif",
    texto: [
        "El testigo ratificó que quien pagó, tanto la ida como la vuelta, fue Marcelo Grandío, quien pasó el fin de semana largo de carnaval con el jefe de Gabinete, sus dos hijos y su esposa. Issin había dicho al diario La Nación y repitió ahora ante la Justicia que adquirió un paquete de 10 vuelos -que incluyen ida y vuelta- por 42.250 dólares a la empresa Alpha Centauri.No obstante, la facturación que consta en el expediente se hizo por separado para el periodista amigo de Adorni. La ida se la cobró Alpha Centauri a la productora ImHouse, y la vuelta la facturó el bróker directamente a Grandío. La factura del viaje de regreso a Buenos Aires se emitió el 9 de marzo -tres semanas después del vuelo- y fue por un valor de 3.000 dólares. Una novedad que surgió de la declaración del piloto es que Marcelo Grandío pagó en efectivo e hizo llegar los billetes a través de un tal “Horacio”, según confiaron a Infobae fuentes del caso. En la testimonial, además, el bróker Issin fue consultado sobre por qué vendió el vuelo a 3.000 dólares, ya que no cerraría con el “precio mayorista” que él pagó por el paquete, y a qué se debe la facturación tardía. El intermediario entre los clientes exclusivos y esta compañía de aviación privada explicó sobre este point que “si el cliente necesita bajar los costos por un determinado motivo, es usual utilizar la ‘pata vacía’ –empty leg, como se le llama en el rubro- para vendérsela a otros clientes”. Y agregó que “puede pasar que el cliente quiera partir del destino B hacia el destino A, por lo que el avión, que está en el destino A, tiene que movilizarse hacia B. Ese tramo (de A hacia B) queda vacío y el cliente puede pedir que se utilice ese espacio para otro pasajero y así aminorar el costo”. Tal fue el caso de Adorni y Grandio, según el piloto: pudieron ubicar en el viaje de ida a otros dos pasajeros y en la vuelta a uno en asientos libres, lo que generó un descuento en el precio. El testigo había sido consultado por la prensa respecto de más precisiones sobre esto cuando salió del Juzgado Federal N° 4, pero prefirió guardar silencio: “No quiero hablar al respecto, pero está aclarado ese point. También aclaré quién pagó”, dijo. El miércoles, en conferencia de prensa, Manuel Adorni había declarado: “El viaje lo pagué, estoy cansado de decirlo, ya no sé cómo explicarlo. La dádiva está si yo no hubiera pagado el viaje”."],
    etiqueta: 1
  },
  { 
    titulo: "Muere Noelia Castillo, la más joven en recibir la eutanasia en España, tras dos años de lucha en los tribunales", 
    introduccion: "Los nuevos chips prometen revolucionar la eficiencia energética en portátiles con arquitectura híbrida avanzada.",
    imagen: "imagen2.avif",
    texto: ["Noelia Castillo, la joven parapléjica de 25 años que había pedido la eutanasia, ha fallecido este jueves después de recibir la muerte asistida en su habitación de la residencia sociosanitaria de Sant Pere de Ribes. Noelia es la paciente más joven de España en recibir la eutanasia y la sexta paciente psiquiátrica de Cataluña en pasar por este procedimiento. Su eutanasia debió llevarse a cabo hace dos años, el 2 de agosto de 2024, pero una orden judicial paralizó el procedimiento in extremis a petición de su padre. Durante dos años, el hombre ha intentado de la mano de Abogados Cristianos impedir la muerte asistida de su hija y ha llevado su demanda hasta el Tribunal Europeo de Derechos Humanos (TEDH), sin éxito. Finalmente, la eutanasia de Noelia quedó programada para este jueves, 26 de marzo. La joven ha fallecido sola y después de despedirse de su madre, tal y como deseaba, en la residencia sociosanitaria de Sant Pere de Ribes donde estaba ingresada y que consideraba como su “zona de confort”, según expresó en una entrevista en el programa Ahora Sonsoles. “Quiero irme ya y dejar de sufrir y punto. Ninguno de mi familia está a favor de la eutanasia. ¿Y yo todo el dolor que he sufrido durante todos estos años?“, expresó durante su entrevista en Antena 3. La joven planeaba ponerse “el vestido más bonito” de su armario y maquillarse de forma “sencilla” para el momento. “Siempre he pensado que quiero morirme guapa”, aseguró. Noelia se crio en una familia desestructurada, marcada por las adicciones y problemas de salud mental de su padre, que hicieron que la joven pasara gran parte de su infancia y adolescencia en centros de menores. El evento que marcó esta historia fue, para ella, una agresión sexual múltiple que sufrió en 2022. Poco después, en octubre del mismo año, la joven intentó suicidarse, incidente por el que quedó parapléjica."],
    etiqueta: 2
  },
  { 
    titulo: "“¿Qué hacés que no le contestás el teléfono a Scaloni?“: la increíble secuencia de la citación de uno de los jugadores de Argentina", 
    introduccion: "Los nuevos procesadores basados en arquitectura Zen 5 establecen nuevos récords de rendimiento.",
    imagen: "imagen3.avif",
    texto: ["La convocatoria a último momento de Agustín Giay a la selección argentina resultó una de las grandes novedades de la nómina del director técnico Lionel Scaloni de cara a los amistosos ante Mauritania y Zambia en La Bombonera. En las últimas horas, se dieron a conocer los entretelones del llamado, que incluyó una verdadera pieza de comedia. Fue su papá el encargado de contar los detalles de lo sucedido con el lateral del Palmeiras, de 22 años. Giay, surgido de San Lorenzo, fue citado para suplir a Gonzalo Montiel, marginado por un desgarro en el isquiotibial. Su reacción, según relató Cadena 3, fue de sorpresa y alegría absoluta. El propio Giay se enteró a través de una llamada insistente de su padre, quien había sido advertido primero por el representante del futbolista. La convocatoria coincidió con días libres que Giay disfrutaba en la capital argentina y motivó un inmediato festejo familiar. El camino que desembocó en la citación comenzó con el rumor transmitido por el apoderado de Giay. “El representante de Agustín me comenta que se rumoreaba que existía la posibilidad de que lo convoquen, pero eran solo comentarios, hasta que 30 minutos después me vuelve a llamar para confirmarlo”, relató Maximiliano Giay a Cadena 3."],
    etiqueta: 3
  },
  { 
    titulo: "LA ERA DE LOS 240Hz EN MONITORES 4K", 
    introduccion: "Los nuevos paneles OLED prometen la combinación perfecta entre calidad de imagen y fluidez.",
    imagen: "vite.svg",
    texto: [
        "Los fabricantes de monitores están llevando la tecnología OLED a nuevos límites con paneles 4K que alcanzan los 240Hz. Esta combinación, hasta ahora imposible, promete la experiencia definitiva tanto para jugadores como para creadores de contenido.",
        "LG y Samsung han anunciado sus primeros modelos con estas características, utilizando nuevas tecnologías de disipación que permiten mantener la calidad de imagen incluso a altas frecuencias de actualización."
    ],
    etiqueta: 3
  },
  { 
    titulo: "SSD PCIE 5.0: VELOCIDADES DE 14GB/s", 
    introduccion: "Las nuevas unidades de almacenamiento prometen reducir los tiempos de carga a prácticamente cero.",
    imagen: "ssd-pcie5.jpg",
    texto: [
        "Los nuevos SSD con interfaz PCIe 5.0 están alcanzando velocidades de lectura secuencial de hasta 14GB/s, duplicando el rendimiento de la generación anterior. Esto permitirá cargar juegos de gran tamaño en cuestión de segundos.",
        "Fabricantes como Samsung y WD ya tienen disponibles sus primeros modelos, que incluyen disipadores activos para mantener las temperaturas bajo control durante transferencias intensivas."
    ],
    etiqueta: 1
  },
  { 
    titulo: "NVIDIA REVELA LA RTX 5090: EL FUTURO DEL RENDIMIENTO GRÁFICO", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "vite.svg",
    texto: [
        "NVIDIA ha presentado oficialmente la RTX 5090, su nueva tarjeta gráfica flagship basada en la arquitectura Blackwell. Con 32GB de memoria GDDR7 y un rendimiento hasta 2.5 veces superior a la RTX 4090, promete revolucionar el gaming y la creación de contenido.",
        "La nueva GPU incorpora tecnología DLSS 4 con generación de múltiples fotogramas, permitiendo experiencias de juego en 8K a 240 FPS. Los primeros benchmarks muestran un rendimiento excepcional en tareas de ray tracing y computación IA.",
        "El lanzamiento está programado para finales de 2024, con un precio que rondaría los $1999 USD para el modelo Founders Edition."
    ],
    etiqueta: 1
  },
  { 
    titulo: "NVIDIA REVELA LA RTX 5090: EL FUTURO DEL RENDIMIENTO GRÁFICO", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "vite.svg",
    texto: [
        "NVIDIA ha presentado oficialmente la RTX 5090, su nueva tarjeta gráfica flagship basada en la arquitectura Blackwell. Con 32GB de memoria GDDR7 y un rendimiento hasta 2.5 veces superior a la RTX 4090, promete revolucionar el gaming y la creación de contenido.",
        "La nueva GPU incorpora tecnología DLSS 4 con generación de múltiples fotogramas, permitiendo experiencias de juego en 8K a 240 FPS. Los primeros benchmarks muestran un rendimiento excepcional en tareas de ray tracing y computación IA.",
        "El lanzamiento está programado para finales de 2024, con un precio que rondaría los $1999 USD para el modelo Founders Edition."
    ],
    etiqueta: 1
  },
  { 
    titulo: "NVIDIA REVELA LA RTX 5090: EL FUTURO DEL RENDIMIENTO GRÁFICO", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "vite.svg",
    texto: [
        "NVIDIA ha presentado oficialmente la RTX 5090, su nueva tarjeta gráfica flagship basada en la arquitectura Blackwell. Con 32GB de memoria GDDR7 y un rendimiento hasta 2.5 veces superior a la RTX 4090, promete revolucionar el gaming y la creación de contenido.",
        "La nueva GPU incorpora tecnología DLSS 4 con generación de múltiples fotogramas, permitiendo experiencias de juego en 8K a 240 FPS. Los primeros benchmarks muestran un rendimiento excepcional en tareas de ray tracing y computación IA.",
        "El lanzamiento está programado para finales de 2024, con un precio que rondaría los $1999 USD para el modelo Founders Edition."
    ],
    etiqueta: 1
  },
  { 
    titulo: "NVIDIA REVELA LA RTX 5090: EL FUTURO DEL RENDIMIENTO GRÁFICO", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "vite.svg",
    texto: [
        "NVIDIA ha presentado oficialmente la RTX 5090, su nueva tarjeta gráfica flagship basada en la arquitectura Blackwell. Con 32GB de memoria GDDR7 y un rendimiento hasta 2.5 veces superior a la RTX 4090, promete revolucionar el gaming y la creación de contenido.",
        "La nueva GPU incorpora tecnología DLSS 4 con generación de múltiples fotogramas, permitiendo experiencias de juego en 8K a 240 FPS. Los primeros benchmarks muestran un rendimiento excepcional en tareas de ray tracing y computación IA.",
        "El lanzamiento está programado para finales de 2024, con un precio que rondaría los $1999 USD para el modelo Founders Edition."
    ],
    etiqueta: 2
  },
  { 
    titulo: "El vuelo de Adorni a Punta del Este: el broker que vendió el pasaje de vuelta declaró que pagó Marcelo Grandío", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "imagen1.avif",
    texto: [
        "El testigo ratificó que quien pagó, tanto la ida como la vuelta, fue Marcelo Grandío, quien pasó el fin de semana largo de carnaval con el jefe de Gabinete, sus dos hijos y su esposa. Issin había dicho al diario La Nación y repitió ahora ante la Justicia que adquirió un paquete de 10 vuelos -que incluyen ida y vuelta- por 42.250 dólares a la empresa Alpha Centauri.No obstante, la facturación que consta en el expediente se hizo por separado para el periodista amigo de Adorni. La ida se la cobró Alpha Centauri a la productora ImHouse, y la vuelta la facturó el bróker directamente a Grandío. La factura del viaje de regreso a Buenos Aires se emitió el 9 de marzo -tres semanas después del vuelo- y fue por un valor de 3.000 dólares. Una novedad que surgió de la declaración del piloto es que Marcelo Grandío pagó en efectivo e hizo llegar los billetes a través de un tal “Horacio”, según confiaron a Infobae fuentes del caso. En la testimonial, además, el bróker Issin fue consultado sobre por qué vendió el vuelo a 3.000 dólares, ya que no cerraría con el “precio mayorista” que él pagó por el paquete, y a qué se debe la facturación tardía. El intermediario entre los clientes exclusivos y esta compañía de aviación privada explicó sobre este point que “si el cliente necesita bajar los costos por un determinado motivo, es usual utilizar la ‘pata vacía’ –empty leg, como se le llama en el rubro- para vendérsela a otros clientes”. Y agregó que “puede pasar que el cliente quiera partir del destino B hacia el destino A, por lo que el avión, que está en el destino A, tiene que movilizarse hacia B. Ese tramo (de A hacia B) queda vacío y el cliente puede pedir que se utilice ese espacio para otro pasajero y así aminorar el costo”. Tal fue el caso de Adorni y Grandio, según el piloto: pudieron ubicar en el viaje de ida a otros dos pasajeros y en la vuelta a uno en asientos libres, lo que generó un descuento en el precio. El testigo había sido consultado por la prensa respecto de más precisiones sobre esto cuando salió del Juzgado Federal N° 4, pero prefirió guardar silencio: “No quiero hablar al respecto, pero está aclarado ese point. También aclaré quién pagó”, dijo. El miércoles, en conferencia de prensa, Manuel Adorni había declarado: “El viaje lo pagué, estoy cansado de decirlo, ya no sé cómo explicarlo. La dádiva está si yo no hubiera pagado el viaje”."],
    etiqueta: 1
  },
  { 
    titulo: "Muere Noelia Castillo, la más joven en recibir la eutanasia en España, tras dos años de lucha en los tribunales", 
    introduccion: "Los nuevos chips prometen revolucionar la eficiencia energética en portátiles con arquitectura híbrida avanzada.",
    imagen: "imagen2.avif",
    texto: ["Noelia Castillo, la joven parapléjica de 25 años que había pedido la eutanasia, ha fallecido este jueves después de recibir la muerte asistida en su habitación de la residencia sociosanitaria de Sant Pere de Ribes. Noelia es la paciente más joven de España en recibir la eutanasia y la sexta paciente psiquiátrica de Cataluña en pasar por este procedimiento. Su eutanasia debió llevarse a cabo hace dos años, el 2 de agosto de 2024, pero una orden judicial paralizó el procedimiento in extremis a petición de su padre. Durante dos años, el hombre ha intentado de la mano de Abogados Cristianos impedir la muerte asistida de su hija y ha llevado su demanda hasta el Tribunal Europeo de Derechos Humanos (TEDH), sin éxito. Finalmente, la eutanasia de Noelia quedó programada para este jueves, 26 de marzo. La joven ha fallecido sola y después de despedirse de su madre, tal y como deseaba, en la residencia sociosanitaria de Sant Pere de Ribes donde estaba ingresada y que consideraba como su “zona de confort”, según expresó en una entrevista en el programa Ahora Sonsoles. “Quiero irme ya y dejar de sufrir y punto. Ninguno de mi familia está a favor de la eutanasia. ¿Y yo todo el dolor que he sufrido durante todos estos años?“, expresó durante su entrevista en Antena 3. La joven planeaba ponerse “el vestido más bonito” de su armario y maquillarse de forma “sencilla” para el momento. “Siempre he pensado que quiero morirme guapa”, aseguró. Noelia se crio en una familia desestructurada, marcada por las adicciones y problemas de salud mental de su padre, que hicieron que la joven pasara gran parte de su infancia y adolescencia en centros de menores. El evento que marcó esta historia fue, para ella, una agresión sexual múltiple que sufrió en 2022. Poco después, en octubre del mismo año, la joven intentó suicidarse, incidente por el que quedó parapléjica."],
    etiqueta: 2
  },
  { 
    titulo: "“¿Qué hacés que no le contestás el teléfono a Scaloni?“: la increíble secuencia de la citación de uno de los jugadores de Argentina", 
    introduccion: "Los nuevos procesadores basados en arquitectura Zen 5 establecen nuevos récords de rendimiento.",
    imagen: "imagen3.avif",
    texto: ["La convocatoria a último momento de Agustín Giay a la selección argentina resultó una de las grandes novedades de la nómina del director técnico Lionel Scaloni de cara a los amistosos ante Mauritania y Zambia en La Bombonera. En las últimas horas, se dieron a conocer los entretelones del llamado, que incluyó una verdadera pieza de comedia. Fue su papá el encargado de contar los detalles de lo sucedido con el lateral del Palmeiras, de 22 años. Giay, surgido de San Lorenzo, fue citado para suplir a Gonzalo Montiel, marginado por un desgarro en el isquiotibial. Su reacción, según relató Cadena 3, fue de sorpresa y alegría absoluta. El propio Giay se enteró a través de una llamada insistente de su padre, quien había sido advertido primero por el representante del futbolista. La convocatoria coincidió con días libres que Giay disfrutaba en la capital argentina y motivó un inmediato festejo familiar. El camino que desembocó en la citación comenzó con el rumor transmitido por el apoderado de Giay. “El representante de Agustín me comenta que se rumoreaba que existía la posibilidad de que lo convoquen, pero eran solo comentarios, hasta que 30 minutos después me vuelve a llamar para confirmarlo”, relató Maximiliano Giay a Cadena 3."],
    etiqueta: 3
  },
  { 
    titulo: "El vuelo de Adorni a Punta del Este: el broker que vendió el pasaje de vuelta declaró que pagó Marcelo Grandío", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "imagen1.avif",
    texto: [
        "El testigo ratificó que quien pagó, tanto la ida como la vuelta, fue Marcelo Grandío, quien pasó el fin de semana largo de carnaval con el jefe de Gabinete, sus dos hijos y su esposa. Issin había dicho al diario La Nación y repitió ahora ante la Justicia que adquirió un paquete de 10 vuelos -que incluyen ida y vuelta- por 42.250 dólares a la empresa Alpha Centauri.No obstante, la facturación que consta en el expediente se hizo por separado para el periodista amigo de Adorni. La ida se la cobró Alpha Centauri a la productora ImHouse, y la vuelta la facturó el bróker directamente a Grandío. La factura del viaje de regreso a Buenos Aires se emitió el 9 de marzo -tres semanas después del vuelo- y fue por un valor de 3.000 dólares. Una novedad que surgió de la declaración del piloto es que Marcelo Grandío pagó en efectivo e hizo llegar los billetes a través de un tal “Horacio”, según confiaron a Infobae fuentes del caso. En la testimonial, además, el bróker Issin fue consultado sobre por qué vendió el vuelo a 3.000 dólares, ya que no cerraría con el “precio mayorista” que él pagó por el paquete, y a qué se debe la facturación tardía. El intermediario entre los clientes exclusivos y esta compañía de aviación privada explicó sobre este point que “si el cliente necesita bajar los costos por un determinado motivo, es usual utilizar la ‘pata vacía’ –empty leg, como se le llama en el rubro- para vendérsela a otros clientes”. Y agregó que “puede pasar que el cliente quiera partir del destino B hacia el destino A, por lo que el avión, que está en el destino A, tiene que movilizarse hacia B. Ese tramo (de A hacia B) queda vacío y el cliente puede pedir que se utilice ese espacio para otro pasajero y así aminorar el costo”. Tal fue el caso de Adorni y Grandio, según el piloto: pudieron ubicar en el viaje de ida a otros dos pasajeros y en la vuelta a uno en asientos libres, lo que generó un descuento en el precio. El testigo había sido consultado por la prensa respecto de más precisiones sobre esto cuando salió del Juzgado Federal N° 4, pero prefirió guardar silencio: “No quiero hablar al respecto, pero está aclarado ese point. También aclaré quién pagó”, dijo. El miércoles, en conferencia de prensa, Manuel Adorni había declarado: “El viaje lo pagué, estoy cansado de decirlo, ya no sé cómo explicarlo. La dádiva está si yo no hubiera pagado el viaje”."],
    etiqueta: 1
  },
  { 
    titulo: "Muere Noelia Castillo, la más joven en recibir la eutanasia en España, tras dos años de lucha en los tribunales", 
    introduccion: "Los nuevos chips prometen revolucionar la eficiencia energética en portátiles con arquitectura híbrida avanzada.",
    imagen: "imagen2.avif",
    texto: ["Noelia Castillo, la joven parapléjica de 25 años que había pedido la eutanasia, ha fallecido este jueves después de recibir la muerte asistida en su habitación de la residencia sociosanitaria de Sant Pere de Ribes. Noelia es la paciente más joven de España en recibir la eutanasia y la sexta paciente psiquiátrica de Cataluña en pasar por este procedimiento. Su eutanasia debió llevarse a cabo hace dos años, el 2 de agosto de 2024, pero una orden judicial paralizó el procedimiento in extremis a petición de su padre. Durante dos años, el hombre ha intentado de la mano de Abogados Cristianos impedir la muerte asistida de su hija y ha llevado su demanda hasta el Tribunal Europeo de Derechos Humanos (TEDH), sin éxito. Finalmente, la eutanasia de Noelia quedó programada para este jueves, 26 de marzo. La joven ha fallecido sola y después de despedirse de su madre, tal y como deseaba, en la residencia sociosanitaria de Sant Pere de Ribes donde estaba ingresada y que consideraba como su “zona de confort”, según expresó en una entrevista en el programa Ahora Sonsoles. “Quiero irme ya y dejar de sufrir y punto. Ninguno de mi familia está a favor de la eutanasia. ¿Y yo todo el dolor que he sufrido durante todos estos años?“, expresó durante su entrevista en Antena 3. La joven planeaba ponerse “el vestido más bonito” de su armario y maquillarse de forma “sencilla” para el momento. “Siempre he pensado que quiero morirme guapa”, aseguró. Noelia se crio en una familia desestructurada, marcada por las adicciones y problemas de salud mental de su padre, que hicieron que la joven pasara gran parte de su infancia y adolescencia en centros de menores. El evento que marcó esta historia fue, para ella, una agresión sexual múltiple que sufrió en 2022. Poco después, en octubre del mismo año, la joven intentó suicidarse, incidente por el que quedó parapléjica."],
    etiqueta: 2
  },
  { 
    titulo: "“¿Qué hacés que no le contestás el teléfono a Scaloni?“: la increíble secuencia de la citación de uno de los jugadores de Argentina", 
    introduccion: "Los nuevos procesadores basados en arquitectura Zen 5 establecen nuevos récords de rendimiento.",
    imagen: "imagen3.avif",
    texto: ["La convocatoria a último momento de Agustín Giay a la selección argentina resultó una de las grandes novedades de la nómina del director técnico Lionel Scaloni de cara a los amistosos ante Mauritania y Zambia en La Bombonera. En las últimas horas, se dieron a conocer los entretelones del llamado, que incluyó una verdadera pieza de comedia. Fue su papá el encargado de contar los detalles de lo sucedido con el lateral del Palmeiras, de 22 años. Giay, surgido de San Lorenzo, fue citado para suplir a Gonzalo Montiel, marginado por un desgarro en el isquiotibial. Su reacción, según relató Cadena 3, fue de sorpresa y alegría absoluta. El propio Giay se enteró a través de una llamada insistente de su padre, quien había sido advertido primero por el representante del futbolista. La convocatoria coincidió con días libres que Giay disfrutaba en la capital argentina y motivó un inmediato festejo familiar. El camino que desembocó en la citación comenzó con el rumor transmitido por el apoderado de Giay. “El representante de Agustín me comenta que se rumoreaba que existía la posibilidad de que lo convoquen, pero eran solo comentarios, hasta que 30 minutos después me vuelve a llamar para confirmarlo”, relató Maximiliano Giay a Cadena 3."],
    etiqueta: 3
  },
  { 
    titulo: "El vuelo de Adorni a Punta del Este: el broker que vendió el pasaje de vuelta declaró que pagó Marcelo Grandío", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "imagen1.avif",
    texto: [
        "El testigo ratificó que quien pagó, tanto la ida como la vuelta, fue Marcelo Grandío, quien pasó el fin de semana largo de carnaval con el jefe de Gabinete, sus dos hijos y su esposa. Issin había dicho al diario La Nación y repitió ahora ante la Justicia que adquirió un paquete de 10 vuelos -que incluyen ida y vuelta- por 42.250 dólares a la empresa Alpha Centauri.No obstante, la facturación que consta en el expediente se hizo por separado para el periodista amigo de Adorni. La ida se la cobró Alpha Centauri a la productora ImHouse, y la vuelta la facturó el bróker directamente a Grandío. La factura del viaje de regreso a Buenos Aires se emitió el 9 de marzo -tres semanas después del vuelo- y fue por un valor de 3.000 dólares. Una novedad que surgió de la declaración del piloto es que Marcelo Grandío pagó en efectivo e hizo llegar los billetes a través de un tal “Horacio”, según confiaron a Infobae fuentes del caso. En la testimonial, además, el bróker Issin fue consultado sobre por qué vendió el vuelo a 3.000 dólares, ya que no cerraría con el “precio mayorista” que él pagó por el paquete, y a qué se debe la facturación tardía. El intermediario entre los clientes exclusivos y esta compañía de aviación privada explicó sobre este point que “si el cliente necesita bajar los costos por un determinado motivo, es usual utilizar la ‘pata vacía’ –empty leg, como se le llama en el rubro- para vendérsela a otros clientes”. Y agregó que “puede pasar que el cliente quiera partir del destino B hacia el destino A, por lo que el avión, que está en el destino A, tiene que movilizarse hacia B. Ese tramo (de A hacia B) queda vacío y el cliente puede pedir que se utilice ese espacio para otro pasajero y así aminorar el costo”. Tal fue el caso de Adorni y Grandio, según el piloto: pudieron ubicar en el viaje de ida a otros dos pasajeros y en la vuelta a uno en asientos libres, lo que generó un descuento en el precio. El testigo había sido consultado por la prensa respecto de más precisiones sobre esto cuando salió del Juzgado Federal N° 4, pero prefirió guardar silencio: “No quiero hablar al respecto, pero está aclarado ese point. También aclaré quién pagó”, dijo. El miércoles, en conferencia de prensa, Manuel Adorni había declarado: “El viaje lo pagué, estoy cansado de decirlo, ya no sé cómo explicarlo. La dádiva está si yo no hubiera pagado el viaje”."],
    etiqueta: 1
  },
  { 
    titulo: "Muere Noelia Castillo, la más joven en recibir la eutanasia en España, tras dos años de lucha en los tribunales", 
    introduccion: "Los nuevos chips prometen revolucionar la eficiencia energética en portátiles con arquitectura híbrida avanzada.",
    imagen: "imagen2.avif",
    texto: ["Noelia Castillo, la joven parapléjica de 25 años que había pedido la eutanasia, ha fallecido este jueves después de recibir la muerte asistida en su habitación de la residencia sociosanitaria de Sant Pere de Ribes. Noelia es la paciente más joven de España en recibir la eutanasia y la sexta paciente psiquiátrica de Cataluña en pasar por este procedimiento. Su eutanasia debió llevarse a cabo hace dos años, el 2 de agosto de 2024, pero una orden judicial paralizó el procedimiento in extremis a petición de su padre. Durante dos años, el hombre ha intentado de la mano de Abogados Cristianos impedir la muerte asistida de su hija y ha llevado su demanda hasta el Tribunal Europeo de Derechos Humanos (TEDH), sin éxito. Finalmente, la eutanasia de Noelia quedó programada para este jueves, 26 de marzo. La joven ha fallecido sola y después de despedirse de su madre, tal y como deseaba, en la residencia sociosanitaria de Sant Pere de Ribes donde estaba ingresada y que consideraba como su “zona de confort”, según expresó en una entrevista en el programa Ahora Sonsoles. “Quiero irme ya y dejar de sufrir y punto. Ninguno de mi familia está a favor de la eutanasia. ¿Y yo todo el dolor que he sufrido durante todos estos años?“, expresó durante su entrevista en Antena 3. La joven planeaba ponerse “el vestido más bonito” de su armario y maquillarse de forma “sencilla” para el momento. “Siempre he pensado que quiero morirme guapa”, aseguró. Noelia se crio en una familia desestructurada, marcada por las adicciones y problemas de salud mental de su padre, que hicieron que la joven pasara gran parte de su infancia y adolescencia en centros de menores. El evento que marcó esta historia fue, para ella, una agresión sexual múltiple que sufrió en 2022. Poco después, en octubre del mismo año, la joven intentó suicidarse, incidente por el que quedó parapléjica."],
    etiqueta: 2
  },
  { 
    titulo: "“¿Qué hacés que no le contestás el teléfono a Scaloni?“: la increíble secuencia de la citación de uno de los jugadores de Argentina", 
    introduccion: "Los nuevos procesadores basados en arquitectura Zen 5 establecen nuevos récords de rendimiento.",
    imagen: "imagen3.avif",
    texto: ["La convocatoria a último momento de Agustín Giay a la selección argentina resultó una de las grandes novedades de la nómina del director técnico Lionel Scaloni de cara a los amistosos ante Mauritania y Zambia en La Bombonera. En las últimas horas, se dieron a conocer los entretelones del llamado, que incluyó una verdadera pieza de comedia. Fue su papá el encargado de contar los detalles de lo sucedido con el lateral del Palmeiras, de 22 años. Giay, surgido de San Lorenzo, fue citado para suplir a Gonzalo Montiel, marginado por un desgarro en el isquiotibial. Su reacción, según relató Cadena 3, fue de sorpresa y alegría absoluta. El propio Giay se enteró a través de una llamada insistente de su padre, quien había sido advertido primero por el representante del futbolista. La convocatoria coincidió con días libres que Giay disfrutaba en la capital argentina y motivó un inmediato festejo familiar. El camino que desembocó en la citación comenzó con el rumor transmitido por el apoderado de Giay. “El representante de Agustín me comenta que se rumoreaba que existía la posibilidad de que lo convoquen, pero eran solo comentarios, hasta que 30 minutos después me vuelve a llamar para confirmarlo”, relató Maximiliano Giay a Cadena 3."],
    etiqueta: 3
  },
  { 
    titulo: "El vuelo de Adorni a Punta del Este: el broker que vendió el pasaje de vuelta declaró que pagó Marcelo Grandío", 
    introduccion: "La nueva generación de tarjetas gráficas promete un salto cuántico en rendimiento con arquitectura Blackwell y 32GB de memoria GDDR7.",
    imagen: "imagen1.avif",
    texto: [
        "El testigo ratificó que quien pagó, tanto la ida como la vuelta, fue Marcelo Grandío, quien pasó el fin de semana largo de carnaval con el jefe de Gabinete, sus dos hijos y su esposa. Issin había dicho al diario La Nación y repitió ahora ante la Justicia que adquirió un paquete de 10 vuelos -que incluyen ida y vuelta- por 42.250 dólares a la empresa Alpha Centauri.No obstante, la facturación que consta en el expediente se hizo por separado para el periodista amigo de Adorni. La ida se la cobró Alpha Centauri a la productora ImHouse, y la vuelta la facturó el bróker directamente a Grandío. La factura del viaje de regreso a Buenos Aires se emitió el 9 de marzo -tres semanas después del vuelo- y fue por un valor de 3.000 dólares. Una novedad que surgió de la declaración del piloto es que Marcelo Grandío pagó en efectivo e hizo llegar los billetes a través de un tal “Horacio”, según confiaron a Infobae fuentes del caso. En la testimonial, además, el bróker Issin fue consultado sobre por qué vendió el vuelo a 3.000 dólares, ya que no cerraría con el “precio mayorista” que él pagó por el paquete, y a qué se debe la facturación tardía. El intermediario entre los clientes exclusivos y esta compañía de aviación privada explicó sobre este point que “si el cliente necesita bajar los costos por un determinado motivo, es usual utilizar la ‘pata vacía’ –empty leg, como se le llama en el rubro- para vendérsela a otros clientes”. Y agregó que “puede pasar que el cliente quiera partir del destino B hacia el destino A, por lo que el avión, que está en el destino A, tiene que movilizarse hacia B. Ese tramo (de A hacia B) queda vacío y el cliente puede pedir que se utilice ese espacio para otro pasajero y así aminorar el costo”. Tal fue el caso de Adorni y Grandio, según el piloto: pudieron ubicar en el viaje de ida a otros dos pasajeros y en la vuelta a uno en asientos libres, lo que generó un descuento en el precio. El testigo había sido consultado por la prensa respecto de más precisiones sobre esto cuando salió del Juzgado Federal N° 4, pero prefirió guardar silencio: “No quiero hablar al respecto, pero está aclarado ese point. También aclaré quién pagó”, dijo. El miércoles, en conferencia de prensa, Manuel Adorni había declarado: “El viaje lo pagué, estoy cansado de decirlo, ya no sé cómo explicarlo. La dádiva está si yo no hubiera pagado el viaje”."],
    etiqueta: 1
  },
  { 
    titulo: "Muere Noelia Castillo, la más joven en recibir la eutanasia en España, tras dos años de lucha en los tribunales", 
    introduccion: "Los nuevos chips prometen revolucionar la eficiencia energética en portátiles con arquitectura híbrida avanzada.",
    imagen: "imagen2.avif",
    texto: ["Noelia Castillo, la joven parapléjica de 25 años que había pedido la eutanasia, ha fallecido este jueves después de recibir la muerte asistida en su habitación de la residencia sociosanitaria de Sant Pere de Ribes. Noelia es la paciente más joven de España en recibir la eutanasia y la sexta paciente psiquiátrica de Cataluña en pasar por este procedimiento. Su eutanasia debió llevarse a cabo hace dos años, el 2 de agosto de 2024, pero una orden judicial paralizó el procedimiento in extremis a petición de su padre. Durante dos años, el hombre ha intentado de la mano de Abogados Cristianos impedir la muerte asistida de su hija y ha llevado su demanda hasta el Tribunal Europeo de Derechos Humanos (TEDH), sin éxito. Finalmente, la eutanasia de Noelia quedó programada para este jueves, 26 de marzo. La joven ha fallecido sola y después de despedirse de su madre, tal y como deseaba, en la residencia sociosanitaria de Sant Pere de Ribes donde estaba ingresada y que consideraba como su “zona de confort”, según expresó en una entrevista en el programa Ahora Sonsoles. “Quiero irme ya y dejar de sufrir y punto. Ninguno de mi familia está a favor de la eutanasia. ¿Y yo todo el dolor que he sufrido durante todos estos años?“, expresó durante su entrevista en Antena 3. La joven planeaba ponerse “el vestido más bonito” de su armario y maquillarse de forma “sencilla” para el momento. “Siempre he pensado que quiero morirme guapa”, aseguró. Noelia se crio en una familia desestructurada, marcada por las adicciones y problemas de salud mental de su padre, que hicieron que la joven pasara gran parte de su infancia y adolescencia en centros de menores. El evento que marcó esta historia fue, para ella, una agresión sexual múltiple que sufrió en 2022. Poco después, en octubre del mismo año, la joven intentó suicidarse, incidente por el que quedó parapléjica."],
    etiqueta: 2
  },
  { 
    titulo: "¿Qué hacés que no le contestás el teléfono a Scaloni?: la increíble secuencia de la citación de uno de los jugadores de Argentina", 
    introduccion: "Los nuevos procesadores basados en arquitectura Zen 5 establecen nuevos récords de rendimiento.",
    imagen: "imagen3.avif",
    texto: ["La convocatoria a último momento de Agustín Giay a la selección argentina resultó una de las grandes novedades de la nómina del director técnico Lionel Scaloni de cara a los amistosos ante Mauritania y Zambia en La Bombonera. En las últimas horas, se dieron a conocer los entretelones del llamado, que incluyó una verdadera pieza de comedia. Fue su papá el encargado de contar los detalles de lo sucedido con el lateral del Palmeiras, de 22 años. Giay, surgido de San Lorenzo, fue citado para suplir a Gonzalo Montiel, marginado por un desgarro en el isquiotibial. Su reacción, según relató Cadena 3, fue de sorpresa y alegría absoluta. El propio Giay se enteró a través de una llamada insistente de su padre, quien había sido advertido primero por el representante del futbolista. La convocatoria coincidió con días libres que Giay disfrutaba en la capital argentina y motivó un inmediato festejo familiar. El camino que desembocó en la citación comenzó con el rumor transmitido por el apoderado de Giay. “El representante de Agustín me comenta que se rumoreaba que existía la posibilidad de que lo convoquen, pero eran solo comentarios, hasta que 30 minutos después me vuelve a llamar para confirmarlo”, relató Maximiliano Giay a Cadena 3."],
    etiqueta: 3
  },
];